/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteRouteImport } from './routes/write'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PapersPaperIdRouteImport } from './routes/papers.$paperId'

const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersPaperIdRoute = PapersPaperIdRouteImport.update({
  id: '/papers/$paperId',
  path: '/papers/$paperId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/review': typeof ReviewRoute
  '/write': typeof WriteRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/review': typeof ReviewRoute
  '/write': typeof WriteRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/review': typeof ReviewRoute
  '/write': typeof WriteRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/compare'
    | '/dashboard'
    | '/discover'
    | '/review'
    | '/write'
    | '/papers/$paperId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/compare'
    | '/dashboard'
    | '/discover'
    | '/review'
    | '/write'
    | '/papers/$paperId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/compare'
    | '/dashboard'
    | '/discover'
    | '/review'
    | '/write'
    | '/papers/$paperId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  ReviewRoute: typeof ReviewRoute
  WriteRoute: typeof WriteRoute
  PapersPaperIdRoute: typeof PapersPaperIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$paperId': {
      id: '/papers/$paperId'
      path: '/papers/$paperId'
      fullPath: '/papers/$paperId'
      preLoaderRoute: typeof PapersPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  ReviewRoute: ReviewRoute,
  WriteRoute: WriteRoute,
  PapersPaperIdRoute: PapersPaperIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
